image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: fichtnerll83
  APP_NAME: gs-rest-service-initial
  REPO: gs-rest-service-initial

stages:
  - build
  - test
  - docker

gradle-build:
  image: "gradle:7.1.1-jdk8"
  stage: build
  script: "gradle bootJar"
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew check
  only:
    - master

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/fichtnerll83/gs-rest-service-initial .
    - docker push registry.gitlab.com/fichtnerll83/gs-rest-service-initial